import { ResourceWithOptions } from 'adminjs';
import { getModelByName } from '@adminjs/prisma';
import { db } from '../../lib/db.js';

export const orderResource: ResourceWithOptions = {
  resource: {
    model: getModelByName('Order'),
    client: db,
  },
  options: {
    navigation: { name: 'Operatiuni', icon: 'ShoppingCart' },
    listProperties: [
      'orderNumber',
      'status',
      'customerName',
      'customerEmail',
      'price',
      'createdAt',
    ],
    filterProperties: ['status', 'customerEmail', 'customerCity', 'createdAt'],
    editProperties: [
      'status',
      'price',
      'shippingCost',
      'trackingNumber',
      'notes',
    ],
    showProperties: [
      'orderNumber',
      'status',
      'customerName',
      'customerEmail',
      'customerPhone',
      'customerCity',
      'description',
      'sourceImageUrl',
      'preferredSize',
      'preferredColor',
      'notes',
      'selectedVariantId',
      'approvedAt',
      'shippingAddress',
      'shippingMethod',
      'shippingCost',
      'trackingNumber',
      'price',
      'paidAt',
      'stripePaymentId',
      'createdAt',
      'updatedAt',
      'shippedAt',
      'deliveredAt',
    ],
    properties: {
      id: { isVisible: { list: false, edit: false, show: true, filter: false } },
      stripeSessionId: { isVisible: false },
      price: { type: 'number' },
      shippingCost: { type: 'number' },
      shippingAddress: { type: 'mixed' },
      description: { type: 'textarea' },
      notes: { type: 'textarea' },
      status: {
        availableValues: [
          { value: 'RECEIVED', label: 'Primita' },
          { value: 'MODELING', label: 'In modelare' },
          { value: 'PENDING_APPROVAL', label: 'Asteapta aprobare' },
          { value: 'APPROVED', label: 'Aprobata' },
          { value: 'PAID', label: 'Platita' },
          { value: 'PRINTING', label: 'In printare' },
          { value: 'SHIPPED', label: 'Expediata' },
          { value: 'DELIVERED', label: 'Livrata' },
          { value: 'CANCELLED', label: 'Anulata' },
        ],
      },
    },
    actions: {
      delete: { isAccessible: false },
      bulkDelete: { isAccessible: false },
    },
  },
};
